<?php if (Mage::helper('rees46_personalization')->isExpertMode() != true): ?>
	<div class="rees46 rees46-recommend" data-type="also_bought" data-item="<?php echo Mage::registry('current_product')->getId() ?>"></div>
	<div class="rees46 rees46-recommend" data-type="similar" data-item="<?php echo Mage::registry('current_product')->getId() ?>"></div>
	<div class="rees46 rees46-recommend" data-type="interesting" data-item="<?php echo Mage::registry('current_product')->getId() ?>"></div>
<?php endif; ?>