<!-- @rees46 -->
<table border="0">
    <tr>
        <td>
            <img src="//cdn.rees46.com/rees46_magento_logo.png" alt="REES46 Logo">
        </td>
        <td style="padding-left: 20px">
            <h1>REES46 Recommendation Engine Overview</h1>
            <p>In REES46 backoffice you will find:</p>
            <ul style="list-style: disc; padding-left: 20px;">
                <li>Recommendation Engine performance reports.</li>
                <li>Trigger mailings management and reports.</li>
                <li>E-mail marketing control and reports.</li>
                <li>Remarketing control and reports</li>
                <li>Product analytics reports.</li>
                <li>Audience segmentation service.</li>
            </ul>
            <p style="margin-top: 20px"><a href="//rees46.com" target="_blank" style="display: inline-block; border: 1px solid #222; padding: 5px 10px; border-radius: 10px; color: #222; text-decoration: none">Go to my REES46 backoffice</a></p>
        </td>
    </tr>
</table>
