<?php
/**
 * Copyright © 2017 REES46, INC. All rights reserved.
 */
?>
<table>
	<tr>
		<td>
			<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA). 'rees46/logo.png'; ?>" alt="REES46">
		</td>
		<td style="padding-left: 20px">
			<h1>REES46 Recommendation Engine Overview</h1>
			<p><?php echo __('Go to your REES46 store dashboard to get the access to:'); ?></p>
			<ul style="list-style: disc; padding-left: 40px;">
				<li><?php echo __('Triggered emails'); ?></li>
				<li><?php echo __('Email marketing tool'); ?></li>
				<li><?php echo __('Personalized search'); ?></li>
				<li><?php echo __('Web push triggered notifications'); ?></li>
				<li><?php echo __('Instant web push notifications'); ?></li>
				<li><?php echo __('Audience segmentation'); ?></li>
				<li><?php echo __('Abandoned cart remarketing tool'); ?></li>
			</ul><br>
			<button onclick="window.open('https://rees46.com/customers/sign_in', '_blank'); return false;" class="primary"><?php echo __('REES46 dashboard'); ?></button><br><br>
			<p><?php echo __('Documentation:'); ?> <a href="<?php echo __('http://docs.rees46.com/display/en/Magento+1.9.x+Extension'); ?>" target="_blank"><?php echo __('http://docs.rees46.com/display/en/Magento+1.9.x+Extension'); ?></a></p>
		</td>
	</tr>
</table>
