<?php if (Mage::helper('rees46_personalization')->isEnabled()): ?>
	<?php $rees46_api_key = $this->helper('rees46_personalization')->getAPIKey(); ?>
	<?php if($rees46_api_key != false): ?>
		<!-- @rees46 -->
		<script src="http://cdn.rees46.com/rees46_script2.js"></script>
		<script type="text/javascript">
			REES46_CART = <?php echo json_encode($this->helper('rees46_personalization')->getCartProductIds()); ?>;
			jQuery(document).ready(function(){
				var user_data = null;
				<?php if (Mage::getSingleton('customer/session')->isLoggedIn()): ?>
					var user_data = {
						id: <?php echo Mage::getSingleton('customer/session')->getCustomer()->getID() ?>,
						email: '<?php echo Mage::getSingleton('customer/session')->getCustomer()->getEmail() ?>'
					};
				<?php endif; ?>
				REES46.init('<?php echo $this->helper('rees46_personalization')->getAPIKey() ?>', user_data, function() {
					<?php $events = Mage::helper('rees46_personalization/event')->getEventsQueue(true) ?>
					<?php foreach($events as $event): ?>
						<?php if($event['name'] == 'view' || $event['name'] == 'cart' || $event['name'] == 'remove_from_cart'): ?>
							REES46.pushData('<?php echo $event['name'] ?>', {
								item_id: '<?php echo $event['data']['item_id'] ?>',
								name: '<?php echo $event['data']['name'] ?>',
								price: '<?php echo $event['data']['price'] ?>',
								is_available: '<?php echo intval($event['data']['is_available']) ?>',
								categories: [<?php echo implode(',', $event['data']['categories']) ?>],
								<?php if($event['data']['recommended_by']): ?>
									recommended_by: '<?php echo $event['data']['recommended_by'] ?>',
								<?php endif; ?>
							});
						<?php endif; ?>
						<?php if($event['name'] == 'purchase'): ?>
							REES46.pushData('purchase', [
								<?php foreach($event['data']['products'] as $product): ?>
									{
										item_id: '<?php echo $product['item_id'] ?>',
										name: '<?php echo $product['name'] ?>',
										price: '<?php echo $product['price'] ?>',
										is_available: '<?php echo intval($product['is_available']) ?>',
										categories: [<?php echo implode(',', $product['categories']) ?>],
										amount: <?php echo $product['amount'] ?>,
										<?php if($product['recommended_by']): ?>
											recommended_by: '<?php echo $product['recommended_by'] ?>',
										<?php endif; ?>
									},
								<?php endforeach; ?>
							],
							'<?php echo $event['data']['order_id'] ?>');
						<?php endif; ?>
					<?php endforeach; ?>

					jQuery('.rees46.rees46-recommend').each(function(){
						var recommenderBlock = jQuery(this);
						var recommenderType = recommenderBlock.data('type');
						switch(recommenderType) {
							case 'interesting':
							case 'also_bought':
							case 'similar':
							case 'recently_viewed':
							case 'buying_now':
								REES46.recommend({
									recommender_type: recommenderType,
									item: recommenderBlock.data('item'),
									cart: REES46_CART
								}, function(data){
									REES46_Recommender_Callback(recommenderType, recommenderBlock, data);
								});
								break;
							case 'popular':
								REES46.recommend({
									recommender_type: recommenderType,
									category: recommenderBlock.data('category')
								}, function(data){
									REES46_Recommender_Callback(recommenderType, recommenderBlock, data);
								});
								break;
							case 'see_also':
								REES46.recommend({
									recommender_type: recommenderType,
									cart: REES46_CART
								}, function(data){
									REES46_Recommender_Callback(recommenderType, recommenderBlock, data);
								});
								break;
						}
					});

					function REES46_Recommender_Callback(recommenderType, block, data) {
						/* @todo: update settings – include parameter for limit minimum recommended items */
						var min_products = 1;
						if(data.length >= min_products) {
							REES46RENDER(
								'/personalization/block',
								{
									ids: data,
									type: recommenderType,
									minimum: min_products,
									block_title: ( block.data('title') || '' )
								},
								function(response) {
									if(response) {
										block.html(response);
									}
								}
							);
						}
					};

					/**
					 * Функция должна всегда получать URL (без параметров) и отдельно params независимо от: POST или GET запрос
					 * @param url
					 * @param attributes
					 * @param callback
					 * @returns {*}
					 * @constructor
					 */
					function REES46RENDER (url, attributes, callback) {

						var params = "ids=" + attributes.ids.join(',') + "&block_title=" + attributes.block_title + "&minimum=" + attributes.minimum + "&type=" + attributes.type;

						/* Обработка результата запроса */
						var handler = function () {
							if (_xml.readyState == 4) {
								if (_xml.status == 200) {
									if (typeof(callback) == 'function') {
										callback(_xml.responseText);
									}
								}
							}
						};

						var handlerIE = function () {
							if (typeof(callback) == 'function') {
								callback(_xml.responseText);
							}
						};

						try {
							var XHR = window.XDomainRequest || window.XMLHttpRequest;
							var _xml = new XHR();
							_xml.withCredentials = "true";
							_xml.open('GET', url + '?' + params, true);
							if (XHR == window.XDomainRequest) {
								_xml.onload = handlerIE;
							} else {
								_xml.onload = handler;
							}
							_xml.send(null);
							this._xml = _xml;
							return this._xml;
						} catch( e ) {
							console.log(e);
						}

						return true;
					};


				});
			});
		</script>
	<?php endif; ?>
<?php endif; ?>
